version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum "dependencies.properties" }}
          - dependencies-

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: dependencies-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum "dependencies.properties" }}

      - run:
          name: Generate allure report
          command: ./gradlew :sample:allureReport

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      # Allure report
      - store_artifacts:
          name: Store Allure report
          path: sample/build/reports/allure-report

  publish_snapshot:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Setup SECRING
          command: mkdir -p secring_dir && echo $SEC_RING | base64 -d > secring_dir/secring.gpg
      - restore_cache:
          keys:
          - dependencies-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum "dependencies.properties" }}
          - dependencies-
      - run:
          name: Publish snapshot
          command: ./gradlew build release-snapshot -Psigning.secretKeyRingFile=$(realpath ~/repo/secring_dir/secring.gpg) -Psigning.keyId=$SEC_RING_KEY_ID -Psigning.password=$SEC_RING_PASSWORD -Possrh.username=$OSSRH_USERNAME -Possrh.token=$OSSRH_PASSWORD
      - run:
          name: Paranoia
          command: rm -rf secring_dir

  publish_release:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Verify version
          command: >-
                   [[ "$(cat gradle.properties | grep -P '^version' | sed 's/version = //g')" == "$(git describe --tags --abbrev=0 | sed 's/^v//g')" ]]
      - run:
          name: Setup SECRING
          command: mkdir -p secring_dir && echo $SEC_RING | base64 -d > secring_dir/secring.gpg
      - restore_cache:
          keys:
          - dependencies-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum "dependencies.properties" }}
          - dependencies-
      - run:
          name: Publish
          command: ./gradlew build release -Psigning.secretKeyRingFile=$(realpath ~/repo/secring_dir/secring.gpg) -Psigning.keyId=$SEC_RING_KEY_ID -Psigning.password=$SEC_RING_PASSWORD -Possrh.username=$OSSRH_USERNAME -Possrh.token=$OSSRH_PASSWORD
      - run:
          name: Paranoia
          command: rm -rf secring_dir

workflows:
  version: 2
  build_and_puslish:
    jobs:
      - build:
          filters:
            tags: { only: /^v.*/ }
      - publish_snapshot:
          requires: [ build ]
          filters: { branches: { only: '/(([0-9x]+\.?){0,3}\/)?develop/' } }
      - publish_release:
          requires: [ build ]
          filters:
            tags: { only: /^v.*/ }
            branches: { ignore: /.*/ }
